### ISSUE TITLE
Exported results_revised.tsv doesn't have headers

### ISSUE THREAD

**Issue by pjl54** [choosehappy/HistoQC#116]
After removing images from the results, the exported results_revised.tsv doesn't have headers and can't be reopened in HistoQC without manually adding headers.

**Comment by choosehappy** [comment]
@foggydae  can you take a look?

**Comment by foggydae** [comment]
@pjl54 Thanks for pointing out. The issue has been solved now. Now the result_revised.tsv will have the same header with the file you open.
