### ISSUE TITLE
having an issue setting up output directory when running qc.pipeline.py

### ISSUE THREAD

**Issue by lumichael24** [choosehappy/HistoQC#117]
Hi,

I'm having trouble running the qc_pipeline as described in the Wiki in Final Notes. I have a .svs file called GTEX-1117F-0126.svs located in my current working directory called HistoQC Workspace. Inside of ./UserInterface/Data I've manually created a directory called output and am running the following line from the command prompt in my working directory:

qc_pipeline.py -o ./output -n 4 C:\...\HistoQC Workspace\*.svs -c config_first.ini --force

I keep getting an error raised from line 268 of qc_pipeline: "Error creating symlink to output .." 

It seems like the 'output' directory is created in my working directory, but from the Wiki I take it that output should have been created in /UserInterface/Data. Any ideas as to what I'm doing wrong?

Thanks!

**Comment by choosehappy** [comment]
You shouldn't have to create any output directories yourself, the app
should do it for you.

The last step of the process is when it creates a symlink from your output
directory to the user interface directory. If directories already exists,
this process will fail, and thus the likely cause of your error message

Does that make sense?

**Comment by lumichael24** [comment]
Thanks for the response. Hmm, I've deleted the output directory that I created and ran the same command from above, but I get the same message. It creates an 'output' directory in my HistoQC Workspace and an 'output' directory in my UserInterface/Data directory.

**Comment by choosehappy** [comment]
That sounds like its working? Are there things in the directory?

**Comment by lumichael24** [comment]
There's an empty HistoQC folder, an error.log and an empty results.tsv in the 'output' directory under UserInterface/Data. In the error.log, there's an error that says: "The filename, directory name, or volume label syntax is incorrect: './output\\*.svs'

That's the error from the following command: 

qc_pipeline.py -o ./output -n 4 C:\Users\...\HistoQC Workspace\*.svs -c config_first.ini --force

with the GTEX svs file located in HistoQC Workspace.

**Comment by choosehappy** [comment]
i think i see a few issues.

first off, shouldn't the command say:
 C:\Users...\HistoQC Workspace\*.svs

instead of

 C:\Users...\HistoQC Workspace*.svs


secondly, i'm not sure how well implemented spaces are absolute filenames, can you rename the directory to something without a space, perhaps replacing the space with an underscore ("_") ?

**Comment by lumichael24** [comment]
Thanks for the help! Did you mean C:\Users...\HistoQC Workspace\*.svs above? I don't see a difference in the two commands above. I changed the directory name to include an underscore, and the syntax error is now fixed. I still get the symlink error, however. 

(qc) C:\Users\lumic\Desktop\qc\HistoQC_Workspace>qc_pipeline.py -o ./output -n 4
 C:\Users...\HistoQC_Workspace\*.svs -c config_first.ini --force
2018-07-10 13:34:52,065 - INFO - Pipeline will use these steps:
2018-07-10 13:34:52,065 - INFO -                BasicModule     getBasicStats
2018-07-10 13:34:53,292 - INFO -                BasicModule     getMag
2018-07-10 13:34:53,292 - INFO -                LightDarkModule getIntensityThre
sholdPercent:tissue
2018-07-10 13:34:53,294 - INFO -                HistogramModule compareToTemplat
es
2018-07-10 13:34:53,295 - INFO -                HistogramModule getHistogram
2018-07-10 13:34:53,296 - INFO -                BrightContrastModule    getContr
ast
2018-07-10 13:34:53,297 - INFO -                BrightContrastModule    getBrigh
tnessGray
2018-07-10 13:34:53,297 - INFO -                BrightContrastModule    getBrigh
tnessByChannelinColorSpace:RGB
2018-07-10 13:34:53,298 - INFO -                BrightContrastModule    getBrigh
tnessByChannelinColorSpace:YUV
2018-07-10 13:34:53,298 - INFO -                SaveModule      saveFinalMask
2018-07-10 13:34:53,299 - INFO -                SaveModule      saveThumbnails
2018-07-10 13:34:53,299 - INFO -                BasicModule     finalComputation
s
2018-07-10 13:34:56,376 - INFO - ----------
2018-07-10 13:34:56,379 - INFO - Previous run detected....overwriting (--force s
et)
2018-07-10 13:34:56,382 - INFO - Number of files detected by pattern:   0
2018-07-10 13:34:58,834 - INFO - ------------Done---------

2018-07-10 13:34:58,835 - INFO - These images failed (available also in error.lo
g), warnings are listed in warnings column in output:
2018-07-10 13:34:58,837 - ERROR - Error creating symlink to output in UserInterf
ace/Data, need to perform this manually for output to work! ln -s C:\Users\lumic
\Desktop\qc\HistoQC_Workspace\output C:\Users\lumic\Desktop\qc\HistoQC_Workspace
\UserInterface\Data\output

(qc) C:\Users\lumic\Desktop\qc\HistoQC_Workspace>

**Comment by choosehappy** [comment]
sorry, it seems there is a formatting issue when typing backslahes

if you look at your command it needs to end with HistoQC_Workspace\\* not HistoQC_Workspace\*


regardless, the main issue is that it says " Number of files detected by pattern: 0",  indicating that for whatever reason your wild card isn't picking up any files. gotta find the files before it can work on them :)


 what if you type "dir" followed by the same string, does anything come up? is it really a "..." after Users as your command shows (which is likely not correct)?

**Comment by lumichael24** [comment]
![dir](https://user-images.githubusercontent.com/22736387/42528829-c167f406-844a-11e8-909e-ebbd5453e943.png)
![err](https://user-images.githubusercontent.com/22736387/42528830-c1787c18-844a-11e8-988e-c20817b62a5c.png)

This is what I get from this command: qc_pipeline.py  -o ./output -n 4 C:\Users\lumic\Desktop\qc\HistoQC_Workspace\*.svs -c config_first.ini --force

There's a backslash after 'Workspace"

**Comment by choosehappy** [comment]
according to the second image you posted, it seems that things have worked as expected, and no errors during processing occurred. 

can you confirm that there is output in " ./output " ?

**Comment by lumichael24** [comment]
yeah thanks! there's a results.tsv of 3kb and I can open it through index.html to view the charts, graphs, etc.! so should I just be able to ignore the symlink error?

**Comment by choosehappy** [comment]
shake and bake!!

the symlink component only needs to succeed once and any subsequent attempts will result in an error. i suspect in this case it did its job earlier on

there should be an easier way of implementing it on my side, but the differences between windows/linux/macos in handling symlinks makes it a bit difficult. lemme have a think about this and see what i come up with

so yes, if you can see output in the user interface ,you can ignore the symlink error : )

looking forward to any feedback you may have

**Comment by lumichael24** [comment]
sounds great! the gtex file was just a dummy svs I found online, I'll try to send feedback when validated data becomes available in a few weeks! thanks for the help!

**Comment by choosehappy** [comment]
are you at upenn? do you by any chance work with michael feldman?

**Comment by lumichael24** [comment]
I go to upenn but don't work with Michael Feldman.

**Comment by choosehappy** [comment]
Fantastic! let me know how it goes. 

and if you'd like to get involved in additional digital pathology research, i would happily make an intro, i work quite closely with him

**Comment by lumichael24** [comment]
sounds good! I'll keep you updated
