### ISSUE TITLE
showing img_mask_use and annotated regions 

### ISSUE THREAD

**Issue by lumichael24** [choosehappy/HistoQC#120]
Is there a way for me to see which regions of the slides have been annotated from the metric collection? e.g. is there anyway for me to display img_mask_use?

**Comment by choosehappy** [comment]
sorry, not sure i understand?

you can see all of the masks in the output directory of the particular
file, and view them interactively using the user interface. (img_mask_use,
is definitely among them)

**Comment by lumichael24** [comment]
sorry, I meant is there a way to see specifically which parts of the original image were cut out? I can currently use the user interface to compare the two pngs (thumb vs. _mask_use) side by side but it's a little difficult to see any differences. 

could this be because my slides have few artifacts or it's just difficult to eyeball the differences at this resolution?

**Comment by choosehappy** [comment]
hmmm....its likely that they have too few artifacts, when large regions are
removed its usually fairly obvious (e.g., compare the tissue vs background
segmentation)

if you want to produce an overlay image, its one line of matlab code:
https://www.mathworks.com/help/images/ref/imshowpair.html


or something like this in python:
        img = color.rgb2gray(img)[:, :, None] #1 channel representation
        mask = mask[:, :, None] * 1.0 #1 channel
        out = np.concatenate((mask, img, mask), 2) #merge channels for fuse


does that help?

**Comment by lumichael24** [comment]
yeah I'll try it out, appreciate it!

**Comment by choosehappy** [comment]
no problem

**Comment by lumichael24** [comment]
Just got some validated data and my team had some questions/feedback:

This is similar to the question I posted earlier. Currently, we are trying to test how similar the masks produced by HistoQC are to the ones that were manually segmented by specialists. That is, we want to see specifically the annotated regions from the slides in HistoQC to see if it matches the annotated regions in some of the soft tissue slides done manually. What I wanted to do was to take all of the annotated regions in the calculations (so the regions not included in the qc calculations) and output them as a difference image, so that we can compare the difference image with the manually annotated image. What I've been trying to do is use diffimg package in Python to test the differences between the thumbnail and the mask_use pngs outputted, or in other words, see the annotated regions that weren't used in the calculations. However, diffimg requires the two images to be in the same color mode (and the output thumb.png is in mode "RGB" and the mask is in mode "L"). I am currently converting the thumb png to monochrome "L" but I'm not so sure this is the right way/acceptable way to do it. This is how I'm modifying the thumbs.png currently to become a black and white image, with the threshold being just a default value. 

`def make_bw_helper(img_array, threshold=200):
	for i in range(len(img_array)):
		for j in range(len(img_array[0])):
			if img_array[i][j] > threshold:
				img_array[i][j] = 0
			else:
				img_array[i][j] = 255
	return img_array`

 One of the suggestions I received was to invert the mask, but I don't think that works since the background where tissue is not located will be inverted as well but we don't care about the background. 

Any tips? Could you explain how the Python overlay code that you sent above works a little further? e.g. what object is img? Were mask and img both initially png files? Also what does the concatenation do? Not too familiar with some of the python packages and how they works (I think I got an PngImageFile attribute with ndim == 2 error when trying the code you sent above). Does converting to gray change the results? 

Also, is there was any way that you could provide an example run of histoqc and share the output directory and input svs file, so that I could have some sort of comparison tool to make sure I'm not using histoqc incorrectly?

Thanks for the help!

**Comment by lumichael24** [comment]
sorry code above is ugly, i'll just post a screenshot instead 

![image](https://user-images.githubusercontent.com/22736387/43543666-c14be094-959e-11e8-951c-dba222b3f14c.png)

**Comment by lumichael24** [comment]
also any comment on the threshold? seems like that might have a problem with dim coloring of some images

**Comment by choosehappy** [comment]
you're trying _way_ too hard

convert image to grayscale:
http://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.rgb2gray
```
>>> from skimage.color import rgb2gray
>>> from skimage import data
>>> img = data.astronaut()
>>> img_gray = rgb2gray(img)
```

threshold it:
```
bw=img_gray>thres_val
```

if you do this for img1 and img2 and can get agreement:

```
import numpy as np
avg_agreement_in_percent=np.mean(img1 &img2)
```

**Comment by lumichael24** [comment]
sorry, not so sure I understand. I get the following error when the img I load is the thumbs.png.

![image](https://user-images.githubusercontent.com/22736387/43544946-7c79e868-95a2-11e8-83ed-6e67b5e982f4.png)

**Comment by choosehappy** [comment]
are you using skimage.io.imread?

**Comment by lumichael24** [comment]
I was using Image.open... my fault...thanks

Do you have a recommendation on what the threshold should be?

**Comment by lumichael24** [comment]
sorry for all the questions, but is there any way the resolution can be larger in the output mask/thumbnails in savemodule.py? right now it seems like the output pngs are close to 25x smaller than the original svs, which makes it a little difficult to analyze.

**Comment by choosehappy** [comment]
i like to aim for the middle of the range and adjust from there

**Comment by choosehappy** [comment]
you can adjust:

```
[SaveModule.saveThumbnails]
image_work_size: 1.25x
small_dim: 500
```

in the config.ini as you see fit

**Comment by lumichael24** [comment]
great, will try that out appreciate it a lot!

do you know how well IHC images work using config.ini? I know the wiki mentions H&E slides but when using config_first.ini with some of the ihc slides it seems like the color of the image may be a little too dull or light. Using config.ini is fine, but with config_first.ini I get something like this in the terminal:

![image](https://user-images.githubusercontent.com/22736387/43591115-92c303d6-9640-11e8-8863-927eefd085a3.png)

**Comment by choosehappy** [comment]
i've not had a chance to test with IHC images, but its unlikely that the same parameters will work universally for all slide types. one of the nice benifits of histoqc is that each of the modules which modifies the mask also produces a thumbnail image. looking at each of those thumbnails it should be easy to spot the module which caused too much tissue to be removed and adjust its parameters

**Comment by lumichael24** [comment]
getIntensityThresholdPercent:dark seems to work really well with some of the folded tissues slides that I have. I'm playing with' upper_threshold' and 'invert' variables in config.ini and can see some visual changes but could you explain what the variables stand for?

**Comment by choosehappy** [comment]
it should be easier for you to answer these questions if you looked at the
code:


map = np.bitwise_and(img > lower_thresh, img < upper_thresh)

so pixels need to be greater than the lower threshold and smaller than the
upper threshold

if invert is set to true, the mask is inverted for final use:

if strtobool(params.get("invert", "False")):
   s["img_mask_" + name] = ~s["img_mask_" + name]

this is in the case where you're able to detect something you don't want
instead of something you do want

i'd suggest setting some breakpoints in the function (make sure to use -n
1) and playing with the ranges in real-time until you find something
suitable
