### ISSUE TITLE
getMag missing?

### ISSUE THREAD

**Issue by lumichael24** [choosehappy/HistoQC#125]
hey choosehappy,

i'm finishing my internship at the end of the week and I'm documenting the process of installing histoqc and using it, so I have a new laptop and am trying to reproduce some of the output by installing histoqc again. 

seems like in BasicModule.py the function getMag is missing? I'm not sure if this is on purpose or not but just wanted to let you know

**Comment by choosehappy** [comment]
its moved, its now in baseImage and doesn't require explicit calling in the
pipeline

**Comment by lumichael24** [comment]
cool, thanks!
