### ISSUE TITLE
BaseImage.getImgThumb cannot parse all case of working size correctly.

### ISSUE THREAD

**Issue by CielAl** [choosehappy/HistoQC#129]
The branch:
`80: if dim.isdigit():
`
is applied to determine whether the working size is under 1 or in (1,100) or larger than 100.
However, the isdigit() is true only all char in the string is 0~9 excluding the ".", which voids the first condition branch (if dim <1 and not dim.is_integer()), hence downsampling factor cannot be recognized.

I suggest using either use regex, or 
move "X" in dim.upper() in the first branch and use float(dim) directly for the conversion. In this case, it is supposed that dim has no 'x' and can be converted if not the error will naturally be raised.

**Comment by choosehappy** [comment]
not sure i completely understand

can you build a minimal example from the existing code showing the error,
and your proposed solution?

**Comment by CielAl** [comment]
Any example with image_work_size = [some decimal number] in the config.ini will show the error, because
str.isdigit() is true iff all characters are 0~9. 
This means a number within (0,1) will never be considered, despite documented and implemented (in the action).

Solution:
(1) Regex can work.
(2) Since in the cases like "1.25X", you directly cast the string before the ending "x" to float without handling the exception, we can do the same thing.
But in this case, it is recommended to
  First: examine whether dim has an ending "X" first
  Second: examine float(dim) in the else block.

If dim is not numeric+"x" or a simple numeric string, it is unsupported and it is normal to raise an error.

**Comment by CielAl** [comment]
According to the Wiki, (also based on the implementation), if working size (i.e. dim) is less than one, than it directly serves as the downsampling factor. The branch condition in line:80 cannot handle this case.

**Comment by CielAl** [comment]
Also, maybe it can be nice to sanitize/examine all parameters in prior so that it won't happen if the pipeline runs for hours and fails for this kind of bugs?

**Comment by choosehappy** [comment]
nice find, all fixed
