### ISSUE TITLE
UI: blanks in path break absdirRe

### ISSUE THREAD

**Issue by skrackow** [choosehappy/HistoQC#135]
To use UI from folder in path with blanks, I changed
var absdirRe = /#outdir:?\s*([^\s]*)\s*\n/;
to
var absdirRe =   /#outdir:?\s*([^\n]*)\n/;
in data_load.js

Not sure if that is a generalisable solution, but blanks in folder names ought to be taken, I'd guess?!

**Comment by choosehappy** [comment]
yup, that seems correct

would you mind submitting a pull request?

**Comment by skrackow** [comment]
I gather my github account would need some permission so I could publish my branch - only I don't know how to request that permission. I am using Visual Studio Code's Github Pull Requests extension.

**Comment by choosehappy** [comment]
thanks for the commit!

closed by #136
