### ISSUE TITLE
Bug in RMS_contrast?

### ISSUE THREAD

**Issue by CielAl** [choosehappy/HistoQC#138]
See https://github.com/choosehappy/HistoQC/blob/master/BrightContrastModule.py#L57
`rms_contrast=np.sqrt(pow(img - img.mean(), 2).sum() /len(img))`

`len(img)` is the # of the row, while rms_contrast is normalized by the area. Shouldn't it be `img.size` instead?

**Comment by choosehappy** [comment]
Correct! 

fixed in 72ba89d218e3b29a21bb3aa426db2af759734650

thanks
