### ISSUE TITLE
The magnification of the input file.

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [choosehappy/HistoQC#145]

**Comment by choosehappy** [comment]
sorry, not sure i understand, it is the _user_ that specifies the magnification which computation takes place:

https://github.com/choosehappy/HistoQC/blob/e680905caafedd09d113493fa448217f5e5efb37/config.ini#L27

I suspect the minimum required magnification will then be the maximal value  present in the config file. note that each module can have its own magnification 

for example this submodule operates at 2.5x:

https://github.com/choosehappy/HistoQC/blob/e680905caafedd09d113493fa448217f5e5efb37/config.ini#L161
