### ISSUE TITLE
deploy in cloud

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [choosehappy/HistoQC#146]
@choosehappy I am trying to deploy histoqc in the google cloud usong cloud run. I created the docker container and deployed it,  But unable to run it. Can you just tell me about the best option i could choose to run histoQC as a service.

**Comment by choosehappy** [comment]
why are you unable to run it? what is the error? not sure what you mean by "as a service"?

**Comment by choosehappy** [comment]
closed due to inactivity
