### ISSUE TITLE
Bar chart display: selecting a minimum number of columns leads to generate an UI issue

### ISSUE THREAD

**Issue by petrovm3** [choosehappy/HistoQC#151]
Select the following columns: filename, type and percent_blurry.
-> no corresponding blurry values are displayed

<img width="746" alt="HistoQC Bar chart display issue -1" src="https://user-images.githubusercontent.com/22933527/75249734-1cbdb000-57d7-11ea-8481-8bde8b0bc3f8.PNG">

Workaround: select an additional column like base_mag
-> the blurry values appear

<img width="749" alt="HistoQC Bar chart display issue -2" src="https://user-images.githubusercontent.com/22933527/75249812-44ad1380-57d7-11ea-8fe4-fb120ce33e26.PNG">

**Comment by choosehappy** [comment]
this is to be expected.

need to have at least 2 "plottable" columns visible for a parallel coordinate plot

"filename" and "type" are not plottable (i.e., they have no numeric value)

if you're interested in looking at only one value, you can try the "bar chart" option (visible on your screenshot)
