### ISSUE TITLE
Integer overflow in ysize issue

### ISSUE THREAD

**Issue by petrovm3** [choosehappy/HistoQC#152]
The processing of a single Aperio file (svs) triggered an error and HistoQC stops processing.

```
Error analyzing file (skipping): 	 <class 'MemoryError'> Out of memory. ('Integer overflow in ysize', ...) 
'<code object saveThumbnails at 0x2aab05369c90, file "/opt/HistoQC/SaveModule.py", line 39>')
```

This issue has been identified when processing a lots of svs file during the same HistoQC processing.
The others SVS went successfully . The file size is reasonable (688MB)

**Comment by choosehappy** [comment]
using this command: 

```
C:\Python37\python.exe C:/temp/HistoQC/qc_pipeline.py -n 1 -c C:\Users\Andrew\Desktop\deleteme\d\config_light-blurry-x5.ini C:\Users\Andrew\Desktop\deleteme\d\84049.svs
```

on the latest build didn't appear to result in any errors on my side:

![image](https://user-images.githubusercontent.com/9681868/75376969-380ce600-58d1-11ea-9ff7-0ed46b5dad9c.png)

The log you provided again looks like it is 84044, which i suspect is corrupted and is the cause of the issues
