### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by maths-qureshi** [choosehappy/HistoQC#154]
I am running histoQC on windows 10 and in an anaconda environment with Python 3.7.3. Although I have added the directory containing the dll into my path and also copied the dll file to C:\Windows\System32, the error still appears.

Please advise what to do pertaining this issue.

Best Regards,

**Comment by choosehappy** [comment]
i don't understand what this means. can you send a screenshot + log file?

**Comment by maths-qureshi** [comment]
Hi,

Here is the entire output (unable to attach a screenshot unfortunately): 
(base) C:\Users\320035951\Documents\Work\Project HistoQC\Work\HistoQC-master_CH>python qc_pipeline.py --help
Traceback (most recent call last):
  File "qc_pipeline.py", line 12, in <module>
    import BaseImage
  File "C:\Users\320035951\Documents\Work\Project HistoQC\Work\HistoQC-master_CH\BaseImage.py", line 8, in <module>
    import openslide
  File "C:\Anaconda3\lib\site-packages\openslide\__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "C:\Anaconda3\lib\site-packages\openslide\lowlevel.py", line 41, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application


I can't find a log file unfortunately. Where is it?

**Comment by choosehappy** [comment]
so it looks like your openslide library isn't correctly installed. i would
suggest starting with a minimal working example to fix that issue first

you can test is by starting a new python interpreter and simply typing
"import openslide", when that works, histoqc will work

depending on your os and manner of installation, you may need to explicitly
define where the library is. that can be done like so:

```
import os
os.environ['PATH'] = 'C:\\research\\openslide\\bin' + ';' +
os.environ['PATH'] #can either specify openslide bin path in PATH, or add
it dynamically
import openslide
```

where the added path is the directory/location of your dll file
