### ISSUE TITLE
Subprocess execution fails because the configuration file cannot be read

### ISSUE THREAD

**Issue by ghadjigeorghiou** [choosehappy/HistoQC#155]
Hello,

I was trying to automate the HistoQC script execution to include it in my workflow. I tried to use the subprocess python module to automatically execute the command through a terminal. I also changed the working directory so that everything would be executed from the HistoQC folder as recommended. However, once the qc-pipeline.py script is called, the execution exits with an error from the configparser indicating that the keyword pipeline could not be found in the config.ini file. I tested the command, being ran from the subprocess method, directly through the terminal and it works fine.

Since the error seems to be related with the subprocess module, I was wondering if there is anyway to import the qc-pipeline script in my code and change the main method to accept the output directories, input directories etc as parameters instead of using a terminal.

For example instead of running the command
"python qc_pipeline.py -o /.TIA/wsi-processed -c config.ini -f -n 6 -s ./TIA/UserTemp/TCGA_22_04.svs "  to be able to do something like:

import qc-pipeline
qc-pipeline.main("./TIA/wsi-processed", config.ini, "f", 6, "s", "./TIA/UserTemp/TCGA_22.svs")

_Error:_
2020-03-02 01:48:30,577 - INFO - no display found. Using non-interactive Agg backend
2020-03-02 01:48:30,739 - INFO - Pipeline will use these steps:
Traceback (most recent call last):
  File "/Users/ghadjigeorgiou/miniconda3/envs/TIA-36/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'pipeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qc_pipeline.py", line 183, in <module>
    processQueue = load_pipeline(config)
  File "qc_pipeline.py", line 113, in load_pipeline
    steps = lconfig.get('pipeline', 'steps').splitlines()
  File "/Users/ghadjigeorgiou/miniconda3/envs/TIA-36/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/ghadjigeorgiou/miniconda3/envs/TIA-36/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'pipeline'

Thanks,
George

**Comment by choosehappy** [comment]
seems the issue is that the config file isn't being loaded correctly,
perhaps you need to use the full path?

**Comment by ghadjigeorghiou** [comment]
I have tried to use the full path but I get the same error.

Should I try to use HistoQC as a python package?

**Comment by choosehappy** [comment]
wel,l i would stick a breakpoint in the config loading part and see why its
not loading properly:

https://github.com/choosehappy/HistoQC/blob/ca7c9edb6c025de9f4716dc5c3b5fb75d048a10c/qc_pipeline.py#L181


i suspect the error is exactly on this line:

https://github.com/choosehappy/HistoQC/blob/ca7c9edb6c025de9f4716dc5c3b5fb75d048a10c/qc_pipeline.py#L113

as it is the first one which attempts to use information from the
configuration file

HistoQC was designed and tested to be a stand-alone application, but that
said i see no reason it couldn't be encapsulated in something else

**Comment by ghadjigeorghiou** [comment]
I managed to get it working by using the subprocess.call command instead of the subprocess.run command. 

Example of code resulting in error:
`sub_out = subprocess.run(['python', histoqc_path, output_arg, main_config, '-f', threads_arg, '-s', path], stdout=PIPE, stderr=PIPE)`

Working code:
`command = 'python ' + histoqc_path + ' ' + output_arg + ' ' + main_config + ' -f ' + threads_arg + ' -s ' + path`
`sub_out2 = subprocess.call(command, shell=True)`

**Comment by choosehappy** [comment]
cool, thanks for the update!
