### ISSUE TITLE
Different results for same slide at different magnifications

### ISSUE THREAD

**Issue by ghadjigeorghiou** [choosehappy/HistoQC#156]
Hello,

I am trying to tune my config.ini pipeline to produce accurate and fast results for the project that i am working on. While experimenting with different values I found out that the area of the tissue detected as suitable for computations was significantly different when the image_work_size magnification was 2.5x and 5x. 

Also,  I noticed that for the 2.5x and 1.5x magnifications the areas specified as not suitable in the resulting fuse and thumbnail images were overlaid with black squares. Is there any way to avoid this? 

Finally, could you please clarify if the image_work_size has to be set to the same value for all 4 modules that use it? For example I only care about the fuse and thumbnail results magnification. Is it possible to specify only those and keep the rest at 1.25x to speed up the computations?

The images were produced with the config.ini workflow provided but I changed:
1. The Base Image image_work_size to 2.5x (original 1.25x)
2. The BasicModule getBasicStats image_work_size to 2.5x (original 1.25x)
3. The SaveModule.saveThumbnails image_work_size to 2.5x (original 1.25x)
4. The BlurDetectionModule.identifyBlurryRegions image_work_size to 2.5x (original 2.5x)

![fuse](https://user-images.githubusercontent.com/31721507/75683251-b6310a00-5c8e-11ea-9f0d-47b7eb7a501c.png)
![thumb_small](https://user-images.githubusercontent.com/31721507/75683254-b7623700-5c8e-11ea-95b3-cdd5a20ee97c.png)
![thumb](https://user-images.githubusercontent.com/31721507/75683255-b7facd80-5c8e-11ea-8291-2cddbdd0be0a.png)

However when I change the same variables except from last one (BlurDetectionModule) to 5x
the images produces are these:
(Due to the size of the 5x images screenshot are provided instead)

<img width="459" alt="Screenshot 2020-03-02 at 14 18 26" src="https://user-images.githubusercontent.com/31721507/75684495-cf3aba80-5c90-11ea-95c0-5961aa2e8942.png">
<img width="458" alt="Screenshot 2020-03-02 at 14 18 53" src="https://user-images.githubusercontent.com/31721507/75684499-d1047e00-5c90-11ea-807f-d0660a205b54.png">

Thanks.

Best,
George

**Comment by choosehappy** [comment]
I suspect that this might be an error with your particular file or
installation. Are you sure you have the whole thing and that it isn’t
corrupted and/or the right library versions?

The way these whole slide image file formats work is that they save the
same image at multiple resolutions. Histoqc uses openslide to read these
different levels. One “level” can be corrupted, while the other are intact,
which would explain why some verions of the image look correct and others
don’t.


Another issue may be related to the particular packages you’re using. Are
you using the docker file?

A user had a similar issue here which was package related:
https://github.com/choosehappy/HistoQC/issues/149


I would suggest 3 options:
1) Try the docker file
2) Try using histoqc with another file, if the behavior doesn’t repeat (I
suspect it won’t given how many people are currently using histoqc), it
speaks to more evidence that something is wrong with your flie
3) Write a very small python program using openslide to loop over your file
at different magnifications and output the results, I suspect you’ll find
an error at one of the levels



A different image_work_size  is currently only supported by
identifyBlurryRegions

That said, adding support to a module should be relatively straightforward,
essentially replacing this line:

img = s.getImgThumb(s["image_work_size"])

To this line:

    img = s.getImgThumb(params.get("image_work_size", "2.5x"))


One needs to be careful though that the final mask is correctly resized and
integrated back into the workflow correctly. identifyBlurryRegions is a
good example of that:

https://github.com/choosehappy/HistoQC/blob/ca7c9edb6c025de9f4716dc5c3b5fb75d048a10c/BlurDetectionModule.py#L30

**Comment by ghadjigeorghiou** [comment]
Hi,

Thank you for your reply. I downgraded my openslide version to 1.1.0 instead of 1.1.1 but the issue was not resolved. I cannot downgrade openslide to any other version as there will be compatibility issues. I also tested the different levels of the picture using the openslide library and no level seems to be corrupted. I used HistoQC with another whole slide image and this behaviour was displayed on those images too. Could you please instruct me on how to download the dockerfile? The HistoQC version I am using right now is the first official release.

Thank you.

Best,
George

**Comment by choosehappy** [comment]
I am sorry to here that and it further suggests that there is a sneaky
library issue

Building a docker image is as simple as typing

docker build .

in the cloned HistoQC directory which contains the associated Dockerfile

you can read more about that process here:
https://stackify.com/docker-build-a-beginners-guide-to-building-docker-images/

**Comment by ghadjigeorghiou** [comment]
Hey,

I tried using HistoQC on a new set of whole slide images and it seems like the issue was fixed. I am not sure how but will do some tests and re-open this issue if I find the solution.

Thank you for your help.

Best,
George

**Comment by choosehappy** [comment]
fascinating! thanks for the update
