### ISSUE TITLE
Tissue mask issue

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#163]
I'm experiencing issues with the mask - see attached image showing very patchy recognition of tissue that appears to be totally valid and relevant for analysis in the original (left). Also the rim of the tissue appears to be cut off based on the blur mask but it's also valid tissue area that I'd like to be considered. Any way to address these issues?
<img width="1679" alt="Screen Shot 2020-03-21 at 11 10 57 AM" src="https://user-images.githubusercontent.com/11299568/77229505-c9841680-6b64-11ea-99c5-3ed29394f469.png">

**Comment by choosehappy** [comment]
sure. each step produces a binary image showing which regions were
*removed* as a result of applying that module/filterfilter.

you can simply find that filter and comment it out from the pipeline (top
of the config.ini)

**Comment by asmagen** [comment]
Sure but that's not quite what I was aiming for. For example the blur rim tissue is required but I suspect the thresholds it's using are too strict so it removes too much. Is there a way to adjust these things instead of removing them?

**Comment by choosehappy** [comment]
of course; simply modify the threshold in
the [BlurDetectionModule.identifyBlurryRegions] section of the config file

**Comment by asmagen** [comment]
Thanks. That works well. Where can I see the definition and list of parameters and value ranges for each module/function?
For example, what is detectSmoothness and how can I adjust it?

**Comment by choosehappy** [comment]
Have you looked at the wiki?  https://github.com/choosehappy/HistoQC/wiki
