### ISSUE TITLE
Output of mask area for processing in python

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#166]
After I reached the optimal pipeline and parameters yielding the correct tissue mask - how do I get it in a format that would allow me to analyze the tissue regions marker staining intensity levels? Either in R or python.

**Comment by choosehappy** [comment]
you can load the mask_use.png, which has the same aspect ratio of the
original image

from there you can identify retained areas (white pixels) and scale
accordingly to access them from the WSI using e.g., openslide, matlab,
bioformats, etc
