### ISSUE TITLE
Bubbles recognition

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#167]
Is there a way to remove these bubbles? (seen as circles in the mask here).
I used `BubbleRegionByRegion.detectSmoothness` but I don't think it does anything with these bubbles.
<img width="663" alt="Screen Shot 2020-03-21 at 4 59 42 PM" src="https://user-images.githubusercontent.com/11299568/77236499-8c844800-6b95-11ea-8ef8-ddabc30dc672.png">

**Comment by choosehappy** [comment]
it helps to provide the corresponding H&E to have an understanding of what
is going on in the original image

were you able to figure out what you needed? Can you share with others what
you ended up doing?

**Comment by asmagen** [comment]
I figured that the pipeline I was using did exclude the rim of the bubble (see black circles above in the mask). The internal part of the bubble are slightly blurry and they may need to be excluded by I didn't get to that. If you have a strategy to do that it would be great to know.

**Comment by choosehappy** [comment]
Looks like they're mutually exclusive from the rest of the binary image

As such, I would likely simply use the remove small object module

```
[MorphologyModule.removeSmallObjects]
min_size: 64
```

And just make the min_size larger than the size of the bubbled regions
