### ISSUE TITLE
Issue with bright/dark area removal somehow affecting the spur step

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#172]
I was trying to exclude the background of the slide better using the bright removal step `LightDarkModule.getIntensityThresholdPercent:tissue` and the dark tissue folds using the dark tissue detection step `LightDarkModule.getIntensityThresholdPercent:darktissue`.
The issue is that playing with these parameters somehow affects the output of `BasicModule.finalProcessingSpur` significantly, where the spur is removing huge parts of the actual tissue.
Here's an example of modifying the bright parameter upper_threshold from .85 to 0.75, showing that it is indeed improving the exclusion of the slide background (in the middle right between the two tissues), but the spur is also removing too much although the description of spur filter doesn't seem to have anything related to this behavior.

Bright .85:
![Li57TCD68 ndpi_bright LightDarkModule getIntensityThresholdPercent tissue upper_threshold  85](https://user-images.githubusercontent.com/11299568/79283101-cf7bc780-7e84-11ea-8960-b51d8d320e5e.png)
Spur (not changing disk_radius: 10 default param):
![Li57TCD68 ndpi_spur LightDarkModule getIntensityThresholdPercent tissue upper_threshold  85](https://user-images.githubusercontent.com/11299568/79283098-cee33100-7e84-11ea-82a6-b34045c000ac.png)
Bright .75:
![Li57TCD68 ndpi_bright LightDarkModule getIntensityThresholdPercent tissue upper_threshold  75](https://user-images.githubusercontent.com/11299568/79283099-cf7bc780-7e84-11ea-964a-136fb30fd9ee.png)
Spur (not changing disk_radius: 10 default param):
![Li57TCD68 ndpi_spur LightDarkModule getIntensityThresholdPercent tissue upper_threshold  75](https://user-images.githubusercontent.com/11299568/79283100-cf7bc780-7e84-11ea-87dc-8141aff46200.png)

**Comment by choosehappy** [comment]
what does the original image look like?

**Comment by choosehappy** [comment]
also, what does your config file look like? this pattern seems more related to the removeFatlikeTissue module and not the finalProcessingSpur module

**Comment by asmagen** [comment]
Here it is:
![stain_example](https://user-images.githubusercontent.com/11299568/79356229-af8fe680-7f0c-11ea-9aae-a8e038378b5c.png)

And the config, based on the config example here with minor modifications:
```
[pipeline]
steps= BasicModule.getBasicStats
    ClassificationModule.byExampleWithFeatures:coverslip_edge
    LightDarkModule.getIntensityThresholdPercent:tissue
    BubbleRegionByRegion.detectSmoothness
    #MorphologyModule.fillSmallHoles
    MorphologyModule.removeSmallObjects
    BlurDetectionModule.identifyBlurryRegions
    BasicModule.finalProcessingSpur
    BasicModule.finalProcessingArea
    HistogramModule.compareToTemplates
    HistogramModule.getHistogram
    BrightContrastModule.getContrast
    BrightContrastModule.getBrightnessGray
    BrightContrastModule.getBrightnessByChannelinColorSpace:RGB
    BrightContrastModule.getBrightnessByChannelinColorSpace:YUV
    DeconvolutionModule.seperateStains
    SaveModule.saveFinalMask
    SaveModule.saveThumbnails
    BasicModule.finalComputations


[BaseImage.BaseImage]
image_work_size = 1.25x

#not yet implemented
confirm_base_mag: False

#three options: relative2mask, absolute, relative2image
mask_statistics = relative2mask

[BasicModule.getBasicStats]
image_work_size = 1.25x

area_threshold: 100
features:  frangi
           laplace
           rgb
           #lbp
           #gabor
           #median
           #gaussian

laplace_ksize: 3

frangi_scale_range: (1,10)
frangi_scale_step: 2
frangi_beta1: .5
frangi_beta2: 15
frangi_black_ridges: True

gabor_theta: 4
gabor_sigma: (1,3)
gabor_frequency: (0.05, 0.25)

lbp_radius: 3
lbp_points: 24
lbp_method: default

median_disk_size: 3

#gaussian_sigma: 1
#gaussian_multichan: False



[ClassificationModule.byExampleWithFeatures:coverslip_edge]
name: coverslip_edge
threshold: 0.9

examples: ./models/coverslip_edge_he/coverslip_edge.png:./models/coverslip_edge_he/coverslip_edge_mask.png

area_threshold: 15
features:  frangi
           laplace
           rgb

dilate_kernel_size: 5

[LightDarkModule.getIntensityThresholdPercent:bubble]
name: bubble
upper_threshold: .94
lower_threshold: .82
upper_variance: 11
invert: true


[LightDarkModule.getIntensityThresholdPercent:tissue]
name: bright
upper_threshold: .85
lower_var: 10

[LightDarkModule.getIntensityThresholdPercent:darktissue]
name: dark
upper_threshold: .25
invert: true


[LightDarkModule.getTissuePercent]
threshold: .75

[LightDarkModule.getDarkTissuePercent]
threshold: .5

[MorphologyModule.removeSmallObjects]
min_size: 250

[MorphologyModule.removeFatlikeTissue]
kernel_size: 10
max_keep_size: 1000
fat_cell_size: 64

[MorphologyModule.fillSmallHoles]
min_size: 1000

[HistogramModule.compareToTemplates]
limit_to_mask: True
bins: 20
templates= ./templates/template1.png
           ./templates/template2.png
           ./templates/template3.png
           ./templates/template4.png

[HistogramModule.getHistogram]
limit_to_mask: True
bins: 20

[BrightContrastModule.getContrast]
limit_to_mask: True


[BrightContrastModule.getBrightnessGray]
limit_to_mask: True

[BrightContrastModule.getBrightnessByChannelinColorSpace:RGB]
limit_to_mask: True


[BrightContrastModule.getBrightnessByChannelinColorSpace:YUV]
limit_to_mask: True
#pick a color space in the list from 'RGB', 'HSV', 'RGB CIE', 'XYZ', 'YUV', 'YIQ', 'YPbPr', 'YCbCr'  : http://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.convert_colorspace
to_color_space: YUV

[SaveModule.saveFinalMask]
overlay: True

[SaveModule.saveThumbnails]
image_work_size: 1.25x
small_dim: 500

[BlurDetectionModule.identifyBlurryRegions]
image_work_size = 2.5x
blur_radius: 50
blur_threshold: .05


[BasicModule.finalComputations]

[BasicModule.finalProcessingSpur]
disk_radius: 10

[BasicModule.finalProcessingArea]
#area_threshold: 90000
area_threshold:  10000

[DeconvolutionModule.seperateStains]
;hed_from_rgb: Hematoxylin + Eosin + DAB
;hdx_from_rgb: Hematoxylin + DAB
;fgx_from_rgb: Feulgen + Light Green
;bex_from_rgb: Giemsa stain : Methyl Blue + Eosin
;rbd_from_rgb: FastRed + FastBlue + DAB
;gdx_from_rgb: Methyl Green + DAB
;hax_from_rgb: Hematoxylin + AEC
;bro_from_rgb: Blue matrix Anilline Blue + Red matrix Azocarmine + Orange matrix Orange-G
;bpx_from_rgb: Methyl Blue + Ponceau Fuchsin
;ahx_from_rgb: Alcian Blue + Hematoxylin
;hpx_from_rgb: Hematoxylin + PAS
stain: hed_from_rgb
use_mask: True


[BubbleRegionByRegion.detectSmoothness]
threshold: .01
kernel_size: 10
min_object_size: 500
```

**Comment by choosehappy** [comment]
can you take a screenshot of all the thumbnails created for this image, for the Bright = .75 setting? or alternatively, can you share the WSI? its not obvious to me why this is happening

**Comment by asmagen** [comment]
You mean the output from each step?
Here it is:
![Li57TCD68 ndpi_fuse](https://user-images.githubusercontent.com/11299568/79377627-fa6c2700-7f29-11ea-987a-b20c414685bf.png)
![Li57TCD68 ndpi_mask_use](https://user-images.githubusercontent.com/11299568/79377634-fe984480-7f29-11ea-99d6-41836ac56b9d.png)
![Li57TCD68 ndpi_deconv_c2](https://user-images.githubusercontent.com/11299568/79377636-fe984480-7f29-11ea-88ec-ca911e279963.png)
![Li57TCD68 ndpi_deconv_c1](https://user-images.githubusercontent.com/11299568/79377637-fe984480-7f29-11ea-8d91-461d004d8a1a.png)
![Li57TCD68 ndpi_deconv_c0](https://user-images.githubusercontent.com/11299568/79377638-ff30db00-7f29-11ea-974b-77e5618fac45.png)
![Li57TCD68 ndpi_hist](https://user-images.githubusercontent.com/11299568/79377640-ff30db00-7f29-11ea-96fb-24c1fc7698c0.png)
![Li57TCD68 ndpi_areathresh](https://user-images.githubusercontent.com/11299568/79377641-ff30db00-7f29-11ea-853b-5ab080a452b7.png)
![Li57TCD68 ndpi_spur](https://user-images.githubusercontent.com/11299568/79377642-ff30db00-7f29-11ea-91d3-fb3e355a2f2a.png)
![Li57TCD68 ndpi_blurry](https://user-images.githubusercontent.com/11299568/79377643-ffc97180-7f29-11ea-99f8-f0526526d19d.png)
![Li57TCD68 ndpi_small_remove](https://user-images.githubusercontent.com/11299568/79377644-ffc97180-7f29-11ea-9a05-9fc89698ae30.png)
![Li57TCD68 ndpi_flat](https://user-images.githubusercontent.com/11299568/79377646-ffc97180-7f29-11ea-8122-5cd8bc7bb2d9.png)
![Li57TCD68 ndpi_bright](https://user-images.githubusercontent.com/11299568/79377647-ffc97180-7f29-11ea-9f4e-421c21c618aa.png)
![Li57TCD68 ndpi_coverslip_edge](https://user-images.githubusercontent.com/11299568/79377648-ffc97180-7f29-11ea-80db-2847f0486bde.png)

**Comment by choosehappy** [comment]
got it, just realized you commented out "MorphologyModule.fillSmallHoles". 

what does the output look like when this is used?

because of the lower threshold, you can see a lot more small islands of pixels inside of result from     LightDarkModule.getIntensityThresholdPercent:tissue

since these holes aren't being filled by the fillsmallholes module, the spur module identifies them as potential places for trimming, and then performs the trimming

**Comment by asmagen** [comment]
I see. I wanted to avoid using that because I wanted the mask to ignore empty areas of any size since I want it to represent the precise tissue cellular area, but I guess filling very small holes isn't going to make much difference. If there is a way to maintain the small holes I would be glad to use it.

**Comment by choosehappy** [comment]
completely understand

if you look at this section of the config:

[MorphologyModule.fillSmallHoles]
min_size: 1000


this parameter is equal to the "area_threshold" parameter used here:


https://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.remove_small_holes

Basically: *The maximum area, in pixels, of a contiguous hole that
will be filled. Replaces min_size.*


Although unintuitive, it describes the maximum size hole which will be
filled in pixel size. looking at your image, you can likely get away with
something on the order of 10

**Comment by asmagen** [comment]
Yeah, that's the threshold I ended up using. Thanks
