### ISSUE TITLE
Image normalization

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#173]
Is there an option to normalize the ndpi images to account for faint slides and stains in such a way they won't fall below the light threshold, and similarly, darker stains wouldn't fall above the dark tissue fold threshold?

Thanks

**Comment by choosehappy** [comment]
unfortunately, that is a whole area of research which has not yet come to a
conclusion

you can read some of my work on the topic (pay particular attention to the
other references, some of which have open-source code available):
https://www.ncbi.nlm.nih.gov/pubmed/27373749

as well as newer stain gan type approaches:
https://arxiv.org/abs/1804.01601

**Comment by asmagen** [comment]
Thanks for the references. I am inclining to not use any normalization since it could bias my quantification of % positive pixels for a given molecule staining, because in lowly expressing stains the normalization would render more than expected pixels to appear positive relative to a highly expressing stain. Do you think this concern applies to the gan type normalizations?

**Comment by choosehappy** [comment]
yes, i think it especially applies to gan normalization approaches. given
their blackbox nature, it will be very hard to predict what the output
would be in all situations. i would take a more hand-crafted approach where
at least one could start to envision what the edge cases might be are
