### ISSUE TITLE
MorphologyModule.py remove_small_holes() got unexpected keyword argument

### ISSUE THREAD

**Issue by LiesMH** [choosehappy/HistoQC#174]
I get an error while running the qc_pipeline on a bunch of TCGA .svs slides. My input: 

`python qc_pipeline -o 'D:/HistoQC' -c config.ini -n 1 'D:/*.svs'`

The error is in the step removeFatLikeTissue, in the module MorphologyModule.py line 51. The error states that remove_small_holes() got an unexpected keyword argument 'min_size'. This happens with all the TCGA slides that I downloaded.

**Comment by choosehappy** [comment]
you're not using the correct versions of the libraries, please use
requirements.txt to install them

alternatively you can use the docker file to create an image with the
correct versions

**Comment by LiesMH** [comment]
Yes I found the problem, in scikit-image 1.16.1 (now 1.17.0, I ran 1.16.2) they renamed the argument 'min_size' to 'area_threshold' for the morphology.remove_small_holes() function. For HistoQC scikit-image an earlier version of scikit-image was probably used. (https://github.com/scikit-image/scikit-image/releases)

**Comment by choosehappy** [comment]
yup. you can see that requirement here:

https://github.com/choosehappy/HistoQC/blob/fdd4a957a16780f2616681a42887970ddc7c396c/requirements.txt#L2
