### ISSUE TITLE
Step by step guidelines to install histoQC?

### ISSUE THREAD

**Issue by Sabrina1948** [choosehappy/HistoQC#176]
Dear all,
Is there a step by step instruction to install the histoQC requirements? I never used python before and now facing challenge to get it together.
Would appreciate your support.
Sincerely,
Sabrina

**Comment by choosehappy** [comment]
you can look at the dockerfile, which has the necessary commands

**Comment by Sabrina1948** [comment]
However, that's for ubuntu. Im using windows. 
Sincerely,
Sabrina

**Comment by choosehappy** [comment]
same idea

1) install open slide for windows
2) install python requirements using pip3 install -r requirements.txt

**Comment by Sabrina1948** [comment]
Dumb question: how to install openslide on windows. 
Im so sorry for being so naive.

**Comment by Sabrina1948** [comment]
by the way, i got python 3.6 (32 bit)

**Comment by Sabrina1948** [comment]
I could install python requirements using  pip3 install -r requirements.txt. Had to activate the pip. 
Now trying to install the openslide. 
Thanks for your hints.
Sincerely,
Sabrina

**Comment by choosehappy** [comment]
moved to #177
