### ISSUE TITLE
installing openslide on windows 10 (64 bit)

### ISSUE THREAD

**Issue by Sabrina1948** [choosehappy/HistoQC#177]
Hi all,
Could anyone please instruct how to install openslide on windows? I downloaded openslide-3.4.0 and also its windows library openslide-win64-20171122. 
Thanks in advance.
Sabrina

**Comment by Rexmiao** [comment]
Hi Sabrina,
   Have you downloaded the python version of API?
   Here is the link: https://openslide.org/download/
   “I downloaded openslide-3.4.0 ” 3.4 does not seem to be the  python API

![image](https://user-images.githubusercontent.com/35504986/82583106-dfac5400-9b60-11ea-8c05-8250e696621a.png)

**Comment by choosehappy** [comment]
Not sure this is correct

on my system, it looks like I'm using the 3.4.1 library version with openslide-python==1.1.1

**Comment by Sabrina1948** [comment]
So do i need to download both  3.4.1 from OpenSlide (stable API) and  1.1.1 from OpenSlide Python interface (stable API)? 
Also which version of Windows Binaries to download. 
I would install them on windows.  it says on histoQC page that ''Openslide binaries will have to be installed separately as per individual o/s instructions''. What command i should give on my CMD?
As you can imagine, I am new to these things. Sorry for asking too many basic questions.
Thanks in advance.
Sincerely,
Sabrina





--

**Comment by Sabrina1948** [comment]
By the way, openslide python is already installed with the command , pip3 install -r requirements.txt. 
only openslide and its windows binary to download and install.
![image](https://user-images.githubusercontent.com/51083517/82656549-3dee3b00-9c24-11ea-9552-249c578ab07e.png)

**Comment by choosehappy** [comment]
openslide and python-openslide are two different component.

openslide is a library, and python-openslide is a connector from python to
use that library.

both need to be installed, python-openslide is done via the requirements
file

i think you definitely want to use a 64-bit python, unless for some reason
your computer can't support it

then you would match that with the 64-bit windows version from the latest
date:

[image: image.png]


you will need to unzip it and either:

a) add the binary directory to the system path

or

b) uncomment this line:

https://github.com/choosehappy/HistoQC/blob/6332121bbb88d50b2535dac06352a6ab660100b6/BaseImage.py#L7

and point it at your installation directory

**Comment by choosehappy** [comment]
![image](https://user-images.githubusercontent.com/9681868/82658916-1e591180-9c28-11ea-80d1-c6cb91532540.png)

**Comment by Sabrina1948** [comment]
Hi again,
I try to add the binary directory to the system path by giving this command on my CMD:
SET PATH=%Path%;C:\python\openslide-win64-20171122\bin
is it the right way? and if so, how to check?
Sincerely,
Sabrina

**Comment by choosehappy** [comment]
run histoqc, if it works, then its the right way : )

**Comment by Sabrina1948** [comment]
next question, how to run histoqc. i dont see any exe. :(

**Comment by choosehappy** [comment]
python qc_pipeline.py --help

will give you usable command line parameters

**Comment by Sabrina1948** [comment]
Yes, it shows up like the attached screenshot. Whats with the error. and which command gives a user interface? sorry to bother you too much.
Sincerely,
Sabrina

![image](https://user-images.githubusercontent.com/51083517/82668052-4309b500-9c39-11ea-9848-0a0e19c6b673.png)

**Comment by choosehappy** [comment]
no problem

@Rexmiao , please arrange a zoom call with @Sabrina1948 to help the installation + running

**Comment by Rexmiao** [comment]
Hi @Sabrina1948 , could you please send me an email at "rxm723@case.edu" so that I can send you the invitation?
