### ISSUE TITLE
HistoQC can not reproduce the same bluriness score between users

### ISSUE THREAD

**Issue by petrovm3** [choosehappy/HistoQC#178]
We have identified why two different users can not get the same blurriness score.

In fact it relies on python library version differences.

The configuration differences are the following (left HistoQC defaults; right mine):

matplotlib==3.1.2 vs mine version 3.0.2
numpy==1.17.4 vs mine version 1.18.1
openslide-python==1.1.1 vs mine version 1.1.1
scikit-image==0.15.0 vs mine version 0.16.2
scikit-learn==0.21.3 vs mine version 0.20.1
scipy==1.3.2 vs mine version 1.1.0
SecretStorage==2.3.1
six==1.11.0 vs mine version 1.12.0

If we use the default from HistoQC source code repository, we get the following error traced in the errors.log:

**_After BasicModule.finalProcessingSpur NO tissue remains detectable! Downstream modules likely to be incorrect/fail|After BasicModule.finalProcessingArea NO tissue remains detectable! Downstream modules likely to be incorrect/fail_**

Mine does not trigger this error.

The comment I would like to bring is that differences in versions seems to impact the results. So keeping reproducible results is the challenge.

What if later HistoQC would need to use new library versions? Would be the results reproducibles?

**Comment by choosehappy** [comment]
yes, this is to be expected and one of the reasons for the dockerization of histoqc, and providing a requirements file. if one needs indefinite reproducibility, they will need to use the same library versions, and in fact one shouldn't expect histoqc to work at all with different versions (as they won't be tested), let alone be reproducible

**Comment by petrovm3** [comment]
Our HPC environment supports [Singularity](https://singularity.lbl.gov/) as a container platform and there is one parameter to provide in order to avoid passing the user local environment to the container when it is called from singularity:
**PYTHONUSERBASE=False**
By doing this we managed to reproduce the same results.

**Comment by choosehappy** [comment]
great, thanks for the update!
