### ISSUE TITLE
HistoQC V2 Dockerfile build: can't find scikit-image 0.18.1

### ISSUE THREAD

**Issue by mariokreutzfeldt** [choosehappy/HistoQC#187]
Hi,

While building the docker container using the provided Dockerfile, I got the following error:
`#6 5.363 Collecting scikit-image==0.18.1 (from -r /opt/HistoQC/requirements.txt (line 2))
#6 5.541   Could not find a version that satisfies the requirement scikit-image==0.18.1 (from -r /opt/HistoQC/requirements.txt (line 2)) (from versions: 0.7.2, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.3, 0.10.0, 0.10.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.15.0, 0.16.1, 0.16.2, 0.17.1, 0.17.2, 0.18.0rc0, 0.18.0rc1)
#6 5.548 No matching distribution found for scikit-image==0.18.1 (from -r /opt/HistoQC/requirements.txt (line 2))

executor failed running [/bin/sh -c cd /opt     && git clone https://github.com/choosehappy/HistoQC.git     && pip3 install -r /opt/HistoQC/requirements.txt]: exit code: 1`

Not sure how to proceed from here.
Thanks,
Mario

**Comment by choosehappy** [comment]
sorry about that, give this a shot

**Comment by surya-narayanan** [comment]
Hi, still facing this issue- installing from source. Which scikit image version should we use?

**Comment by tasvora** [comment]
Can you paste the error that you see in your console.
As the requirements.txt does have the correct version of scikit image, not sure what is the issue that you see?
