### ISSUE TITLE
os.symlink problem on Win10 OS, no admin permissions

### ISSUE THREAD

**Issue by elijahedmondson** [choosehappy/HistoQC#188]
When the scripts are run as Admin, they perform find. But we are not able to get Admin permissions for the QC computers -- is there a way around this? 

Traceback (most recent call last):
  File "qc_pipeline.py", line 263, in <module>
    os.symlink( origin, target, target_is_directory=True)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:

**Comment by choosehappy** [comment]
This isn't a strict requirement, and in fact works quite poorly in Windows since it doesn't support symlinks

The only requirement is to copy the output directory into the "HistoQC\UserInterface\Data" directory, and then you should be able to use the index.html as expected

**Comment by elijahedmondson** [comment]
Yes perfect, moving output worked

**Comment by choosehappy** [comment]
Great, thanks for the update!
