### ISSUE TITLE
UI: otsu and otsulocal masks aren't displayed because not in global_config.js

### ISSUE THREAD

**Issue by bswhite** [choosehappy/HistoQC#192]
Masks created by getIntensityThresholdOtsu either with global thresholding (suffix _otsu.png) or local thresholding (suffix _otsulocal.png) don't display in the UI because they aren't listed in DEFAULT_IMAGE_EXTENSIONS in histoqc/ui/UserInterface/scripts/global_config.js.

Further, getIntensityThresholdOtsu hardcodes its suffix to "otsu" or "ostulocal." Other modules seem to instead leave this user-defined as in:
name = params.get("name", "classTask")

I suggest:
1. Removing name = "otsu" and name += "local" from getIntensityThresholdOtsu and replacing with name = params.get("name", "classTask")
Note that allowing a user-supplied name would allow us to display the corresponding mask in the UI by co-opting a name in global_config.js that is unused in the configuration (e.g., _bright might be used since the getIntensityThresholdPercent that outputs it would likely be replaced by getIntensityThresholdOtsu).
2. Adding _otsu.png and _otsulocal.png to global_config.js. This isn't technically necessary given (1), but will cover the common case where a user names their module 'otsu'. 

I'm happy to make such a pull request if @choosehappy agrees and would like me to.

**Comment by choosehappy** [comment]
Thanks for your comments!

This Otsu method as you point out has not been well developed nor maintained. It was one of the earlier attempts at detecting tissue, but didn't appear to work very robustly across the full gamut of slides. The major challenge here being that tissue detection is the first step in the pipeline, and if that doesn't work, the rest of it doesn't work properly.

In the latest version of histoqc we've provided a new approach ( `LightDarkModule.minimumPixelIntensityNeighborhoodFiltering`) which has worked quite well for me across both IHC + H&E images, and has now become my "go to" approach.

That said, I am of course happy to accept a pull request for your suggested improvements, just want to make sure that the use case you're aiming to address wouldn't already be addressed by that new detection approach? 

If it is, and works well, we may even consider officially retiring the Otsu approach and removing it from the code base

Thoughts?

**Comment by bswhite** [comment]
Thanks for the background on Otsu and your experience with it.

My use case is the same -- tissue vs slide separation as an early / first step in the pipeline. I also experienced that it doesn't work as well as I would like. In particular, many of my H&E images have large, localized light areas near the tissue periphery that Otsu is calling background/slide. This makes sense to me -- my understanding of Otsu is that it will work best when there is a clear bimodal distribution of light and dark intensities, which isn't the case in these slides. So, I will almost certainly be abandoning it.

That said, I vote for making these proposed changes and for keeping Otsu in your code base. In my (limited) experience, it is popular. For example, it is our lab's go to approach. And it is used by one of the cell segmentation methods (HoverNet) we apply. Otsu is also attractive in principle because it has no parameters (at least if applied globally). I think for these reasons many people will at least want to experiment with Otsu to see how it performs. There is a good chance they abandon it for another of your approaches (LightDarkModule.minimumPixelIntensityNeighborhoodFiltering), but I know that I would appreciate at least being able to empirically evaluate them myself.

If you are interested, I've just made a simple pull request here:
https://github.com/choosehappy/HistoQC/pull/193

Thanks!

**Comment by choosehappy** [comment]
Completely agree with all your points. It is fast, parameter-free, and a popular good starting point; though I hope anyone reading this will also take a look at the other more sophisticated approaches we provide which appear to work more robustly in most of our cases.

That said, there will be other situations (e.g., trichrome stain) where otsu is likely going to crush it


So, I thank you for your efforts and have just merged your pull request. you should be all good to go!
