### ISSUE TITLE
typo in seperateStains - minor issue

### ISSUE THREAD

**Issue by kaczmarj** [choosehappy/HistoQC#194]
hello, there is a typo in `seperateStains`. it should be `separateStains`. i can submit a pr for this, but I realize changing this could break backwards compatibility. how should i proceed? thanks.

https://github.com/choosehappy/HistoQC/blob/979d25b703af311f4b7ee63bd1cfb5ba3086606d/histoqc/DeconvolutionModule.py#L16-L17

**Comment by choosehappy** [comment]
eeeeeeeeembarassing....

yes, if you submit the PR, i will accept it :)
