### ISSUE TITLE
Configuration Changes needed

### ISSUE THREAD

**Issue by tasvora** [choosehappy/HistoQC#201]
In order to run Histoqc , I had to add the full path for the config file
path to the config file
python -m histoqc -c histoqc/config/config_v2.1.ini -n 3 "*.svs"

Need to resolve this.

**Comment by choosehappy** [comment]
I think the logic should be

if args.config file exists --- > config.read (this is currently done)
if args.config file does not exist, try to load a template with that name
(this is not done)
if args.config does not exist, load the template default (this is currently
done)
