### ISSUE TITLE
Adding Bounding Box feature

### ISSUE THREAD

**Issue by tasvora** [choosehappy/HistoQC#202]
[openslide.PROPERTY_NAME_BOUNDS_X]

**Comment by choosehappy** [comment]
i think it essentially involves this file:

https://github.com/choosehappy/HistoQC/blob/9c15c1767de0a9d1d54fa87b3e819a225b0fad00/histoqc/BaseImage.py#L138

and putting the read_region lines within an if-statement, that either the user has selected a bounding_Box = true (in the config.ini) in which case (0,0) becomes the bounding box region, or bounding_box = false in which case it says at (0,0)
