### ISSUE TITLE
Support for ndpi Hamamatsu format

### ISSUE THREAD

**Issue by iamalonso** [choosehappy/HistoQC#207]
@choosehappy Is there a possibility to support the NDPI file? as I understand, OpenSlide does support these proprietary files from the manufacturer Hamamatsu. I've been trying to transform from **ndpi** to **svs** but can't find a tool that can do it.

Could you give me any suggestions?

**Comment by choosehappy** [comment]
I am not entirely sure what your question is here, openslide does support NDPI, and as such histoqc can and has used them in the past successfully. no need to convert to another format : )
