### ISSUE TITLE
LightDarkModule.getIntensityThresholdPercent

### ISSUE THREAD

**Issue by mrigank-srivastava** [choosehappy/HistoQC#213]
Hi!

Line number 65 in the 'getIntensityThresholdPercent(s, params)' function in the 'LightDarkModule.py' file is computing the standard deviation for the 'img' object, however, the variable name 'img_var' seems to want the variance which is also used in further comparisons within the function. All config files in which the above module is used specify the variance (upper and/or lower). Below is the code snippet from the function.

```python
    lower_thresh = float(params.get("lower_threshold", -float("inf")))
    upper_thresh = float(params.get("upper_threshold", float("inf")))

    lower_var = float(params.get("lower_variance", -float("inf")))
    upper_var = float(params.get("upper_variance", float("inf")))

    img = s.getImgThumb(s["image_work_size"])
    img_var = img.std(axis=2) ## this one

    map_var = np.bitwise_and(img_var > lower_var, img_var < upper_var)

    img = color.rgb2gray(img)
    map = np.bitwise_and(img > lower_thresh, img < upper_thresh)

    map = np.bitwise_and(map, map_var)

    s["img_mask_" + name] = map > 0
```

Can you provide any explanation for comparing standard deviation with the variance given in the config files?
Thanks!!

**Comment by choosehappy** [comment]
OOops. thanks for spotting that, it looks like the variable name is
incorrect. For consistency with previous results, everything should be
based on standard deviation

would you be willing to submit a pull request to address this issue? : )

**Comment by mrigank-srivastava** [comment]
> would you be willing to submit a pull request to address this issue?

Yes
