### ISSUE TITLE
Trying to Build HistoQC Through Terminal

### ISSUE THREAD

**Issue by brijeshwar2002** [choosehappy/HistoQC#214]
I am having issues to build HistoQC through terminal. Following is the error I am getting (subprocess-exited-with-error).

I have installed all the packages and patches to build HistoQC.

Looking forward to hearing from you.

Thank you!

**Comment by choosehappy** [comment]
Sorry, this unfornuately isn't enough information for us to provide help

can you please provide describe step by step what you did, the output of
each of those steps, and the resulting errors?

feel free to use screenshots, etc

as well, it would be good to see the output from "pip freeze" to ensure the
proper libraries are installed

**Comment by brijeshwar2002** [comment]
Is there any tutorial video on how to build the software through terminal, or any step by step guide from which I can understand how to use HistoQC.

**Comment by choosehappy** [comment]
we have a wiki page set up which discusses generally how to use it:

https://github.com/choosehappy/HistoQC/wiki

and as well, the readme file contains the  setup information:

https://github.com/choosehappy/HistoQC/blob/master/Readme.md
