### ISSUE TITLE
Black regions with SVS images

### ISSUE THREAD

**Issue by chlmarchal** [choosehappy/HistoQC#215]
Hi! 

I tried to do an analysis on the same image, but on different formats: NDPI and SVS.
For the NDPI file, the analysis works fine. However, for the SVS image, I get black regions on the result images. I attached an example on an image I get for the SVS image.

![CMU-1 svs_fuse](https://user-images.githubusercontent.com/91737269/165524342-90fe0f6e-0963-4e9e-a6dd-ed706cf7a6bc.png)

The two images I used are the following:
[CMU-1.ndpi](https://cytomine.com/collection/cmu-1/cmu-1-ndpi)
[CMU-1.svs](https://cytomine.com/collection/cmu-1/cmu-1-svs)

I noticed I have the same issue with other svs images, i.e. the CMU-2 image (that can also be found [here](https://cytomine.com/collection)).
Do you have an idea about why I have those black regions with the svs image? Maybe is there a parameter in the config file I have to change? 

Thank you!

**Comment by choosehappy** [comment]
pixman  Can you take a look at this issue?

https://github.com/choosehappy/HistoQC/issues/149

have you tried the docker file? if you have (and it works) then the issue
is with the environment.

usually it is an issue with pixman

you can read more here:

https://github.com/openslide/openslide/issues/291
