### ISSUE TITLE
Pixels_to_use 1000x smaller?

### ISSUE THREAD

**Issue by barrettMCW** [choosehappy/HistoQC#216]
I wanted to calc % pixels left, it seems like the value of pixels_to_use is 1000x smaller than it should be? Maybe I'm misinterpretting what it represents or just being stupid but dividing pixels_to_use by width*height is giving me ~.0005 vs a more reasonable ~.5 (50%). Any ideas? The masks themselves look good.

**Comment by choosehappy** [comment]
pixels_to_use is based on the magnification/size of img_mask_use:

https://github.com/choosehappy/HistoQC/blob/979d25b703af311f4b7ee63bd1cfb5ba3086606d/histoqc/BasicModule.py#L25

so if wanted the %, you would use the width*height of the *_thumb.png image as the denominator

**Comment by barrettMCW** [comment]
Ahhh that'll do it. I was using the full WSI w*h as the denominator. Thanks!

**Comment by choosehappy** [comment]
Boom! you're welcome!
