### ISSUE TITLE
unable to install numpy and scipy from requirements.txt file

### ISSUE THREAD

**Issue by surya-narayanan** [choosehappy/HistoQC#218]
Hi, 

I am trying to install HistoQC into my system. I get the following error when I try to install the requirements.txt file in a new conda env with python 3.10-

`ERROR: Could not build wheels for numpy, scipy, which is required to install pyproject.toml-based projects`

Have you faced this before?

**Comment by choosehappy** [comment]
I have not...have you tried this though?
https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe
