### ISSUE TITLE
Config files and LightDarkModule.getIntensityThresholdPercent

### ISSUE THREAD

**Issue by guillermojp** [choosehappy/HistoQC#219]
Hi! Thanks a lot for the tool, it's very useful.

I'm paraphrasing a bit from another issue (#213).

[Line 61](https://github.com/choosehappy/HistoQC/blob/master/histoqc/LightDarkModule.py#L61) in the 'getIntensityThresholdPercent(s, params)' function in the 'LightDarkModule.py' file expects the variable name to be called "lower_variance". However, in the config files, the variable is often referenced as "lower_var", which causes the function to take the default value "-inf":

[config.ini](https://github.com/choosehappy/HistoQC/blob/master/histoqc/config/config.ini#L100)
[config_first.ini](https://github.com/choosehappy/HistoQC/blob/master/histoqc/config/config_first.ini#L34)
[config_light.ini](https://github.com/choosehappy/HistoQC/blob/master/histoqc/config/config_light.ini#L98)
[config_v2.1.ini](https://github.com/choosehappy/HistoQC/blob/master/histoqc/config/config_v2.1.ini#L112)
[config_clinical](https://github.com/choosehappy/HistoQC/blob/master/histoqc/config/config_clinical.ini#L100)

Thanks

**Comment by choosehappy** [comment]
you are totally right, i see now with #213 they agreed to submit a pull
request but it looks like that never came to fruition :-\

would you be interested in submitting a pull-request to address this issue
so we can close em both?

**Comment by guillermojp** [comment]
Sure, but... Do I change the names of the variables in the config files or the name of the variable read in the module? Either way some users will experience bugs.

**Comment by choosehappy** [comment]
I would change the ones in the module, since that is the "single point" of
error? what do you think?
