### ISSUE TITLE
The error message "OSError: [Errno 22] Invalid argument" while running the tool

### ISSUE THREAD

**Issue by ShangWeiKuo** [choosehappy/HistoQC#227]
Hello, @choosehappy

When I run the command **python -m histoqc -c default -n 56 "temp.ndpi"**, I got the error message of OSError[Errno 22] like the picture below. 

![image](https://user-images.githubusercontent.com/26018604/209781419-e82f9ab8-5c14-4155-9384-09790d99ed51.png)

How should I do to solve this error?

**Comment by choosehappy** [comment]
hmmm...this is a weird one...can you confirm that there is write permission in that directory and that the sub directory was successfully created? is error.log created? is the harddrive full?

also using -n 56 would launch *56* workers, is that the intended action? if you're just getting setup using a much lower number will likely make your life a bit more stable : )
