### ISSUE TITLE
Bug in data/__init__.py

### ISSUE THREAD

**Issue by measty** [choosehappy/HistoQC#232]
I think there is an issue that's been caused by merging in PR #228 

as the line:
https://github.com/choosehappy/HistoQC/blob/74b47453e9a3be513d0bda801807dafe51998511/histoqc/data/__init__.py#L50
throws an error `package_resource_copytree() missing 1 required positional argument: 'result'` due to the change that that PR made to the line:
https://github.com/choosehappy/HistoQC/blob/74b47453e9a3be513d0bda801807dafe51998511/histoqc/data/__init__.py#L120

**Comment by choosehappy** [comment]
Thanks for the message, we're on it! @nanli-emory can you please take a look? this is related to your commit

**Comment by nanli-emory** [comment]
Hi @choosehappy fixed the missing 'result' parameter when the **package_resource_copytree** is called

**Comment by choosehappy** [comment]
seems reasonable to me, @measty can you confirm that this works?

**Comment by measty** [comment]
Hi,

It needed a few additional changes to work for me. Those were:

https://github.com/choosehappy/HistoQC/blob/74b47453e9a3be513d0bda801807dafe51998511/histoqc/data/__init__.py#L50

modify this line also to be `package_resource_copytree('histoqc.data', rsrc, self._tmp_dir, None)`

And then after that a further problem appeared, which can be fixed by changing:
https://github.com/choosehappy/HistoQC/blob/74b47453e9a3be513d0bda801807dafe51998511/histoqc/LightDarkModule.py#L62-L65
to be
```
    # set lower standard deviation
    lower_std = float(params.get("lower_var") or params.get("lower_std") or "-inf")
    # set upper standard deviation
    upper_std = float(params.get("upper_var") or params.get("upper_std") or "inf")
```

**Comment by nanli-emory** [comment]
Hi @measty, I changed the code you pointed out. Sorry, it was my mistake on the incorrect variable name and missed revising the **package_resource_copytree** call. Please check [PR 233](https://github.com/choosehappy/HistoQC/pull/233) and let me know if you have any questions.

**Comment by measty** [comment]
looks ok to me, i'll close the issue now. Thanks!
