### ISSUE TITLE
How to provide your own examples

### ISSUE THREAD

**Issue by DianaM228** [choosehappy/HistoQC#235]
Hello, thank you for this very useful tool. 

I would like to know if there is a particular way to provide examples (for example images with pen marks and the respective mask). Even if I give the full path (if I save it in a folder other than data/pen/1k_version ) or if I save the images in the folder /data/pen/1k_version, I get the following error **<class 'ValueError'> Inappropriate argument value (of correct type). Unknown label type: 'continuous'**. As you can see in the following text, the examples you provide are prefixed by **/.histoqc_pkg_data_tmpke77zkry/**

`2023-02-08 14:35:49,789 - INFO - 57654.svs -    ClassificationModule.byExample: pen_markings
/runs/Pitzalis_Data_Fusion309169/scripts**/.histoqc_pkg_data_tmpke77zkry/**./pen/1k_version/pen_green.png:/runs/Pitzalis_Data_Fusion-309169/scripts/**.histoqc_pkg_data_tmpke77zkry/**./pen/1k_version/pen_green_mask.png
/runs/Pitzalis_Data_Fusion309169/scripts/**.histoqc_pkg_data_tmpke77zkry/**./pen/1k_version/pen_red.png:/runs/Pitzalis_Data_Fusion-309169/scripts/.histoqc_pkg_data_tmpke77zkry/./pen/1k_version/pen_red_mask.png
/runs/Pitzalis_Data_Fusion-09169/scripts/.histoqc_pkg_data_tmpke77zkry/./pen/1k_version/pen_black.png:/runs/Pitzalis_Data_Fusion-309169/scripts/.histoqc_pkg_data_tmpke77zkry/./pen/1k_version/pen_black_mask.png
/runs/Pitzalis_Data_Fusion-309169/scripts/pen/custom/pen_red_custom.png:/runs/Pitzalis_Data_Fusion-309169/scripts/pen/custom/pen_red_mask_custom.png
2023-02-08 14:35:49,789 - INFO - 57654.svs - Training model ClassificationModule.byExample:pen_markings
2023-02-08 14:36:01,780 - ERROR - /root/workdir/Pitzalis_Data/Subset1/CD3/PAT054/57654.svs - Error analyzing file (skipping):    <class 'ValueError'> Inappropriate argument value (of correct type). Unknown label type: 'continuous'
2023-02-08 14:36:01,786 - INFO - ----------Done-----------

2023-02-08 14:36:01,786 - INFO - There are 1 explicitly failed images (available also in error.log), warnings are listed in warnings column in output
2023-02-08 14:36:01,787 - INFO - /root/workdir/Pitzalis_Data/Subset1/CD3/PAT054/57654.svs       <**class 'ValueError'> Inappropriate argument value (of correct type). Unknown label type: 'continuous'**
<code object byExampleWithFeatures at 0x7f887b896d90, file "/root/anaconda3/envs/pitfusion/lib/python3.10/site-packages/histoqc/ClassificationModule.py", line 150> `

**Comment by nanli-emory** [comment]
Hi @DianaM228 would you mind sharing your config file? I try to reproduce the issue. Thanks.

**Comment by DianaM228** [comment]
Hello @nanli-emory thanks for answering. Here is the file. The custom Examples paths for the module ClassificationModule.byExampleWithFeatures:pen_markings are the commented ones in the respective section. 
[pitzalis_ihc.txt](https://github.com/choosehappy/HistoQC/files/10694904/pitzalis_ihc.txt)

**Comment by DianaM228** [comment]
Hey, 
I just noticed that running histoQC creates a temporary folder (as shown in the image). In this temporary  folder the files of the histoQC data folder are copied. So, it seem this is the path where histoQC is looking for my custom examples. Is this behavior normal in histoQC?

![TmpFolderHistoQc](https://user-images.githubusercontent.com/25314698/217780692-fb5a799e-2882-4401-a878-0a07d24be436.PNG)

**Comment by nanli-emory** [comment]
Currently, the code does that. It looks "normal" from the code. But I need to do more tests to make sure it's not the reason causing your problem because I suspect that is the reason for your problem. Do you have more information that provides me? Thanks,

**Comment by DianaM228** [comment]
Hello, 
I noticed that the images are being copied from the path "/root/anaconda3/envs/pitfusion/lib/**python3.1**/site-packages/histoqc/" and not from the folder where the error appeared "/ root/anaconda3/envs/pitfusion/lib/**python3.10**/site-packages/histoqc"
I put my images in this first path and now they are copied to the temporary fordel (they are recognized as examples by declaring "./pen/1k_version/pen_red_custom.png:./pen/1k_version/pen_red_mask_custom.png" in the config file).

However, now I am having problems with the mask i am using, could you please tell me if there are any restrictions regarding the characteristics of the mask used?

<img width="726" alt="HistoqcError2" src="https://user-images.githubusercontent.com/25314698/218792558-c3924820-c3c0-4517-b5e7-c87248de41fd.PNG">


![pen_red_mask_custom](https://user-images.githubusercontent.com/25314698/218792693-e1125ed1-8ad3-4ab3-9c2f-56a0f9649565.png)


Thanks!

**Comment by DianaM228** [comment]
Hello, 
After following the new error, I found that it is related to number of labels for the classifier. This error is then related to the "mask" image i am using. When executing line 182 of the "ClassificationModule.py" module, 
`mask = io.imread(ex[1], as_gray=True).reshape(-1, 1)`
the original examples are loaded as np.arrays with values 0 or 255. In my case, they are loaded with values 0 and 1. So, by including my example the labels generated are 0, 1, 255. 
Then, I need to check the way I save the mask as png, because they were originally .nii files.

Thanks!

**Comment by choosehappy** [comment]
Great! Looks like you got it figured out? you want to be saving it as a one channel image, with 0 as the negative class and 1 or 255 as the maximal class (if saving as float or uint8, respectively)
