### ISSUE TITLE
Annotation module not working

### ISSUE THREAD

**Issue by noemiLuna** [choosehappy/HistoQC#237]
How to include the annotation module in the configuration templates list? Is it possible to have an example on how to run the annotation module? 
I tried to run it through the following command:
**python -m histoqc -c example_XML -n 3 "C:/Users/input_pattern/*.svs"** 
after I copied the configuration file HistoQC/AnnotationModule/config_example_XML.ini into HistoQC/histoqc/config directory.
The following error occured:
"KeyError: "no configuration template found under key 'example_XML'""

Thank you in advance for your help!

**Comment by choosehappy** [comment]
you have two options based on this code:

https://github.com/choosehappy/HistoQC/blob/1df6420ea830088f8578e53faf7ffab3b3bf2194/histoqc/__main__.py#L79

1) use an absolute path to the file and it will be loaded
2) modify your naming convention to match that expected of config files:

https://github.com/choosehappy/HistoQC/blob/1df6420ea830088f8578e53faf7ffab3b3bf2194/histoqc/config/__init__.py#L17

essentially it needs to start with and look like "config_***.ini"

**Comment by noemiLuna** [comment]
Solved removing se second underscore!
Thank you!

**Comment by noemiLuna** [comment]
I have another little question about the annotation file format. For what concern annotations in XML, the code is compatible with the Aperio XML file format. What about the JSON file format? Was also this one obtained with Aperio annotation tool or is it related to other scanners?

**Comment by choosehappy** [comment]
The json is of type geojson, which is a fairly standard way of representing objects - https://geojson.org/

looking at the provided geojson, it seems to have been made via the tool Qupath

**Comment by noemiLuna** [comment]
Thanks a lot!
