### ISSUE TITLE
ClassificationModule:pixelWise

### ISSUE THREAD

**Issue by noemiLuna** [choosehappy/HistoQC#238]
Is it possible to have an example of the required tsv file? What information should it hold?
According to documentation, pixelWise classification "Applies an RGB based classifier to the image whose values come from a user inputed TSV" but I don't understand which kind of information should it contain. Features extracted from a training set?  
Thank you in advance for the clarification!

**Comment by choosehappy** [comment]
Yes, its right here:

https://github.com/choosehappy/HistoQC/blob/master/histoqc/data/models/pen_markings_he/he.tsv

Its a fairly naive approach, it treats the 3 channels as a feature vector, and uses the positive and negative classes you provide to train a classifier, and then applies that classifier
