### ISSUE TITLE
UI: resulting images visualization

### ISSUE THREAD

**Issue by noemiLuna** [choosehappy/HistoQC#239]
![Immagine1](https://user-images.githubusercontent.com/40336418/219012328-e29fb5b2-f25f-4945-8bbf-c46b536a3fb6.png)

Is it normal that the resulting images are not imported automatically in the UI? I also tried to import them one at a time but what happens is that a new page is opened with the single image making impossible a comparison between the group of images

**Comment by choosehappy** [comment]
no no they should definitely be loaded automatically into the UI when the results.tsv is loaded. this type of situation is normally caused when the images aren't where the front end thinks they are. 

if you run this type of a command:
```
python -m histoqc.ui
```

it will likely say something like:

```
HistoQC data directory: 'D:\temp\HistoQC'
```

and your output directories are expected to be within that subdirectory. if they're not you can also specify their location via command line parameters

**Comment by noemiLuna** [comment]
Thanks you!
