### ISSUE TITLE
UI: CorhortFinder issues

### ISSUE THREAD

**Issue by nijunnijun** [choosehappy/HistoQC#241]
After clicking on CorhortFinder, it opens up file explorer. What file should I select here? I tried results.tsv but nothing happened. BTW, Instruction button is not working. Is there user guide some where? Also, do you have a recommended browser? I tried both Edge and Chrome but the UMAP doesnt seem to display correctly.

**Comment by choosehappy** [comment]
results.tsv is the correct file. i have always used chrome with great success. I'm hoping @nanli-emory can help you out?

**Comment by nanli-emory** [comment]
Hi @nijunnijun,
Do you mind if you can share your results.tsv file with me?

**Comment by nijunnijun** [comment]
![image](https://user-images.githubusercontent.com/65668421/221856307-3a29f5d8-f9b6-41a0-8836-742040ff35fd.png)
[results.zip](https://github.com/choosehappy/HistoQC/files/10850317/results.zip)
Hi @nanli-emory, I am attaching the results.tsv and a screenshot to show nothing happens after selecting this file in the CorhortFinder. Is there a separate repo I need to download for the finder? Thanks.

**Comment by nanli-emory** [comment]
Hi @nijunnijun,
The **results.tsv** that you shared was generated by HistoQC. You have to use this file as input file to run [CohortFinder](https://github.com/choosehappy/CohortFinder). The CohortFinder will generate a new **results_cohortfinder.tsv** files.
You have to select the **results_cohortfinder.tsv** file after you click on CorhortFinder btn.

results_cohortfinder.tsv should include cluster info.

workflow should be:
1. run HistoQC and generate results.tsv (1) files.
2. run CohortFinder and use HistoQC's output as CohortFinder's input to generate  results_cohortfinder.tsv(2)
3. run HistoQC.UI and load results.tsv(1),  select the results_cohortfinder.tsv(2) file  after clicking on CorhortFinder btn

Hi @choosehappy, please correct me if my understand of the workflow is incorrect.
