### ISSUE TITLE
Only left portion of slide HistoQC'd?

### ISSUE THREAD

**Issue by aday00** [choosehappy/HistoQC#249]
For us, the final HistoQC images only show the leftmost half or third of the WSI pyramid.  The WSI data are completely intact and can be dumped via openslide-write-png.  Is there a HistoQC bounding box that is less than the entire slide?

**Comment by nanli-emory** [comment]
Hi @aday00, 
Could you help me narrow down the issue by answering some questions?

1. Could you share your **config.ini** file?
2. Do you set **enable_bounding_box** parameter as true on the **BaseImage.BaseImage** module?
3. How many WSI images do you run on HistoQC? Do all WSI output images/masks have the same issues?
4. Can you share or point to one of the WSI images you use?

 Thanks

**Comment by aday00** [comment]
Hi @nanli-emory,

Thanks for your fast follow-up and guidance!
1. As far as I can tell, this happens if we use config_v2.1.ini or a slightly modified ini.  I operate in an environment where it's not really possible to move files out.
2. BaseImage.BaseImage only has image_work_size=1.25x, in_memory_compression=True, confirm_base_mag:False, and mask_statistics=relative2mask.  There is no enable_bounding_box in the ini file. 
3. I've tried this on both private and TCGA slides.  Seems reproducible.  I'll continue tests, particularly on TCGA, because that's more straightforward to share privately.
4. Is it possible to exchange email addresses via a direct message, or may I email one of the authors (e.g. Andrew or Anant)?  We have a collaboration with Anant.

Thanks

**Comment by nanli-emory** [comment]
Hi @aday00, your comment is very helpful. I will test on my local and see if I can reproduce the issue. This is my email nan.li@emory.edu. Thanks.

**Comment by choosehappy** [comment]
can you share a screenshot of the result from the TCGA case? does it look like this? https://github.com/choosehappy/HistoQC/issues/215

**Comment by aday00** [comment]
No, it doesn't look like that.  It's just truncated a bit.  Maybe we can have a screenshare sometime?  Will follow up via email.

**Comment by aday00** [comment]
Nan Li got this working for me, needed to update to https://github.com/choosehappy/HistoQC/commit/a99916c2ceaa61c7ae5d75600f10d3fb553041fc

The code we were running was from https://github.com/choosehappy/HistoQC/commit/1df6420ea830088f8578e53faf7ffab3b3bf2194

Many thanks Nan!
