### ISSUE TITLE
AnnotationModule did not exclude holes from GeoJSON's polygon and multipolygons

### ISSUE THREAD

**Issue by CielAl** [choosehappy/HistoQC#258]
Per the standard of GeoJSON (example here: https://gist.github.com/andrewharvey/971b9db1900a62efa7635f6a6d337ae7#file-polygon-with-a-hole-geojson), for a `Polygon` geometry type, only the first vertices list represents the outer ring while the rest are holes.

However, the current implementation considers all inner rings as individual polygons - and the corresponding pixel regions are set to 1 in `mask_out_annotation`. Naturally, these operations are also redundant since all holes are definitely inclusive inside the outer ring: https://github.com/choosehappy/HistoQC/blob/master/histoqc/AnnotationModule.py#L68

I recommend re-model the template point-set functions to return Tuple[point_set,  List[point_set]] therefore the mask_out_annotation can correctly identify holes.

I doubt the ImageScope's xml has a well-defined behavior to assign holes into a specific node/attribute so perhaps we can ignore that part?

**Comment by choosehappy** [comment]
how does e.g., qupath import/export geojson to meet these requirements?

ultimately, i suspect that is where most folks will be getting their geosjon from, so should be compatible with that tool?

**Comment by CielAl** [comment]
> how does e.g., qupath import/export geojson to meet these requirements?
ultimately, i suspect that is where most folks will be getting their geosjon from, so should be compatible with that tool?

Note that GEOJson is standardized and their specification is [here](https://datatracker.ietf.org/doc/html/rfc7946). Therefore all GEOjson strictly follow some schema. Particularly for polygons, if I understand their specification correctly, the coordinates would be "one outer ring followed by multiple inner rings" format, which is also the showcase holed-polygon geojson example I attached above.

Qupath officially supports the Geojson (de-)serialization exactly for [this reason](https://qupath.readthedocs.io/en/0.4/docs/advanced/exporting_annotations.html). XML annotations defined by different software, on the other hand, are not standardized. (e.g., which attributes to hold annotation class is haphazardly defined in different cases). So I guess the "holes" (also supported by brush tools of QuPath) are naturally supported by QuPath. 

The point is that if we employ the AnnotationModule to select a subset of pixel regions and if these regions contain huge holes, the current implementation will definitely include inner rings and give undesired results.



PS, Pete's own words in the above Qupath documentation link are:

> A common question regarding QuPath is whether it supports XML annotations.
> 
> In practice, this requires a specification (schema) describing exactly the structure of the XML required; different software may use XML in totally different ways.
> 
> What I think many people may mean is ‘ImageScope XML’, because this has been around for a long time. QuPath does not support this because there is not (to my knowledge) any public schema describing it; rather, QuPath focusses on well-defined, open formats.
> 
>

**Comment by choosehappy** [comment]
I took a look at Qupath documentation and github but can't seem to find any indication that it supports the GeoJSON holes functionality. have you tested it out? can you provide an example geojson which works?

my concern is only of one that users are most likely to use a tool, like qupath, to make their geojson files, so histoqc should at minimum support the equivalent formatting/presentation without breaking. it can of course support a *superset* if needed, but it shouldn't come at the cost of not being compatible with the most likely use case

see what i mean?

**Comment by CielAl** [comment]
> my concern is only of one that users are most likely to use a tool, like qupath, to make their geojson files, so histoqc should at minimum support the equivalent formatting/presentation without breaking. it can of course support a superset if needed, but it shouldn't come at the cost of not being compatible with the most likely use case

Agree. Here goes the example annotation/geojson.

Sample - Arbitrary rectangle (outer) polygon with a hole (removed by brushing tool).
![image](https://github.com/choosehappy/HistoQC/assets/10933828/0ce003a4-1572-4ade-9d12-7b0f52360ffa)



Sample gson exported by QuPath - first point set in the coordinate fields corresponding to the rectangle apparently.
![image](https://github.com/choosehappy/HistoQC/assets/10933828/a036ecaa-f1df-4f94-b6d8-d1fb76903187)

Note that QuPath uses Google's gson library to input/output geojson (which is a well-defined schema), and then we know that QuPath itself supports holes in its qpdata, plus the fact that QuPath can both import and export annotations to/from geojson files with minimal information loss (e.g., certain geometry like circles will be turned into polygons), therefore QuPath must support the hole functionality of GeoJSON otherwise there is no way it can read holes back from the exported GeoJsons.

Another point worth noting in our own documentation the GeoJSON must not be exported as "FeatureCollection" (which is used in the demo QuPath script for annotation exportation) but as individual "Feature"s.

I have some existing codes that may cover this issue but I assume it is not urgent to fix at this moment before Nan clears up the WSI handles? 

(I believe the GsonTools are in its io module but we will definitely be buried with that amount of code to understand all undocumented details.)

**Comment by CielAl** [comment]
PS: in the above example, the rectangle and the circle are considered as a single polygon in QuPath (not different objects or MultiPolygons). The circle is created by the `erasing mode` of [brush tools](https://qupath.readthedocs.io/en/0.4/docs/reference/shortcuts.html). If we use our qupath-to-binary groovy script the hole can also be identified in the resulting binary mask.

However, the current implementation in HistoQC will consider each inner ring as an individual filled polygon, filling them with ones, and naturally, these polygons are already inside the bigger outer ring polygon that is also filled by one. As a result, the current implementation cannot identify any holes -- which may be quite crucial depending on the specific annotation shape -- what if the users specifically remove large bulk of unwanted regions in QuPath (e.g., if they only want peri-tumor regions or they remove the keratin pearls)?

**Comment by choosehappy** [comment]
perfect, thanks. you've addressed all my questions. agree we should go forward with it

do you have some code to address? don't think it needs to wait for the WSI handle work to be completed?

**Comment by CielAl** [comment]
> perfect, thanks. you've addressed all my questions. agree we should go forward with it
> 
> do you have some code to address? don't think it needs to wait for the WSI handle work to be completed?

It is a subset of my annotation processing code to read/parse the ImageScope XML or GeoJSON into individual closed regions with labels. I will migrate it to AnnotatetionModule when I am back from family business this weekend.

You are right that we don't need to be worried about the WSI handle since this module is pretty much not coupled with that.

**Comment by choosehappy** [comment]
Super thanks, looking forward to it!

**Comment by CielAl** [comment]
> Super thanks, looking forward to it!

Pushed. #259
