### ISSUE TITLE
`pipeline` in results.tsv header is not tab separated

### ISSUE THREAD

**Issue by adamjtaylor** [choosehappy/HistoQC#267]
In the output `results.tsv`, the header row starting with the key `pipeline` is separated by a colon and a space from its associated value:

https://github.com/choosehappy/HistoQC/blob/325baa20c5df642147b9838dcb6447cdab2847e9/histoqc/__main__.py#L119

However the other header row key-value pairs are separated by a colon and a tab

https://github.com/choosehappy/HistoQC/blob/325baa20c5df642147b9838dcb6447cdab2847e9/histoqc/__main__.py#L118-L122

This makes parsing the results.tsv headers somewhat confusing.

I would propose making it separated by a tab for consistency

**Comment by choosehappy** [comment]
wow, would you look at that...totally agree. @jacksonjacobs1  can you push a fix?
