### ISSUE TITLE
Optionally save Geojson masks for Qupath & DSA compatibility

### ISSUE THREAD

**Issue by jacksonjacobs1** [choosehappy/HistoQC#298]
Add functionality to export geojson masks at the base magnification level instead of binary png masks.

@choosehappy , @nanli-emory would it be more appropriate to implement this as a standalone module or as a function  in `saveModule.py`?

**Comment by choosehappy** [comment]
hmmm...thinking out loud here....we have an annotation module. does it make sense to put it in there and also add a "load" feature? that may be going overboard however -- not really sure how many folks would use it?

**Comment by CielAl** [comment]
@jacksonjacobs1 @choosehappy 

Geojson might be more inefficient in space than binary png...
Also agree that AnnotationModule and the histoqc.annotation package would be a more semantically matched place to implement the functions than SaveModule. Just add some interface to export xml/geojson from mask (e.g., cv2 + geojson) and create something like AnnotationModule.exportAnnotation which export specified keys in BaseImage as xml or geojson and that's all. 

Use shapely's affine transformation to upscale the coordinates properly.

**Comment by choosehappy** [comment]
geojson is desirable because its drag/drop-able into other common tools, 
like qupath. the can't be said for binary masks unforunately (or at this 
time)

**Comment by CielAl** [comment]
> geojson is desirable because its drag/drop-able into other common tools, like qupath. the can't be said for binary masks unforunately (or at this time)

Yes. Not trying to dispute that just as a reason why this geojson output should be in the AnnotationModule (export as annotation file that can be used by other tools) rather than in SaveModule (as a replacement of mask, which it can't)
