### ISSUE TITLE
Unable to process .bif files 

### ISSUE THREAD

**Issue by Himanshunitrr** [choosehappy/HistoQC#312]
I am trying to process .bif files but got, what can i do to process them? 
```

2024-07-24 21:37:49,673 - INFO - /data/TMH 4.bif        <class 'openslide.lowlevel.OpenSlideError'> An error produced by the OpenSlide library.    Import this from openslide rather than from openslide.lowlevel.     Bad direction attribute "LEFT"
<code object __init__ at 0x7c5e202a6b30, file "/opt/HistoQC/venv/lib/python3.8/site-packages/histoqc/BaseImage.py", line 21>

```

**Comment by jacksonjacobs1** [comment]
Although Openslide officially supports .bif, there are some open issues related to this file format. For instance: https://github.com/openslide/openslide/issues/234

Can you check if you can open & read the image with the openslide python interface?

**Comment by Himanshunitrr** [comment]
Checked, get the same error while directly reading it

**Comment by jacksonjacobs1** [comment]
In that case the issue seems to be with Openslide and not HistoQC. I would recommend bumping the issue I linked to -- maybe the openslide folks can provide support.

**Comment by Himanshunitrr** [comment]
the workaround it is to convert those .bif files to .tif files using [tifffile](https://github.com/DigitalSlideArchive/tifftools)
