### ISSUE TITLE
countTissuePieces() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Himanshunitrr** [choosehappy/HistoQC#315]
I am trying to run HistoQC on a dataset but I am getting: 

> 2024-08-14 18:03:37,380 - WARNING - HS14-29933 1A .ndpi - Mask file '/opt/HistoQC/.histoqc_pkg_data_tmpk_mr7_8v/./pen/1k_version/pen_black_mask.png' is not a binary image. Automatically converting to binary...
> 2024-08-14 18:09:02,260 - ERROR - /data/HS14-29933 1A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> 2024-08-14 18:16:22,410 - ERROR - /data/HS16-26406 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> 2024-08-14 18:17:11,626 - ERROR - /data/HS12-32993 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given......

How to resolve this

**Comment by CielAl** [comment]
> I am trying to run HistoQC on a dataset but I am getting:
> 
> > 2024-08-14 18:03:37,380 - WARNING - HS14-29933 1A .ndpi - Mask file '/opt/HistoQC/.histoqc_pkg_data_tmpk_mr7_8v/./pen/1k_version/pen_black_mask.png' is not a binary image. Automatically converting to binary...
> > 2024-08-14 18:09:02,260 - ERROR - /data/HS14-29933 1A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> > 2024-08-14 18:16:22,410 - ERROR - /data/HS16-26406 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> > 2024-08-14 18:17:11,626 - ERROR - /data/HS12-32993 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given......
> 
> How to resolve this

@choosehappy @jacksonjacobs1 @nanli-emory 
Seems like the ```BasicModule.countTissuePieces``` does not define a params signature following the paradigm of custom modules invoked in pipelines, yet it is invoked as a module in the config files.
